# Generated by Django 4.0.5 on 2022-08-20 23:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_userinfo_cash'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastApiAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
