# Generated by Django 4.0.5 on 2022-08-22 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_delete_lastapiaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='cash',
            field=models.DecimalField(decimal_places=20, max_digits=255),
        ),
    ]
