# Generated by Django 4.0.5 on 2022-08-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_userinfo_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='cash',
            field=models.DecimalField(decimal_places=100, max_digits=1000),
        ),
    ]
