# Generated by Django 4.0.5 on 2022-08-23 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_userinfo_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='cash',
            field=models.DecimalField(decimal_places=50, max_digits=500),
        ),
    ]
