# Generated by Django 4.0.5 on 2022-08-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_userinfo_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='assets',
            field=models.TextField(blank=True, default=''),
        ),
    ]
