# Generated by Django 4.0.5 on 2022-08-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_userinfo_anonymous_alter_userinfo_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='added_cash',
            field=models.DecimalField(decimal_places=50, default=30000, max_digits=500),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='leaderboard_portfolio_value',
            field=models.DecimalField(decimal_places=50, default=0, max_digits=500),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='cash',
            field=models.DecimalField(decimal_places=50, default=30000, max_digits=500),
        ),
    ]
