# Generated by Django 4.0.5 on 2022-08-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_userinfo_added_cash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='price_history',
            field=models.TextField(default='30000'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='leaderboard_portfolio_value',
            field=models.DecimalField(decimal_places=50, default=30000, max_digits=500),
        ),
    ]
