# Generated by Django 4.0.5 on 2022-08-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='socials',
            field=models.TextField(blank=True),
        ),
    ]
