# Generated by Django 4.0.5 on 2022-08-27 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_leader_image_leader_socials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leader',
            name='image',
        ),
    ]
