# Generated by Django 4.0.5 on 2022-09-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_remove_leader_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestUserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('anonymous', models.BooleanField(default=False)),
                ('light_mode', models.BooleanField(default=False)),
                ('assets', models.TextField(blank=True, default='')),
                ('cash', models.DecimalField(decimal_places=50, default=40000, max_digits=500)),
                ('added_cash', models.DecimalField(decimal_places=50, default=40000, max_digits=500)),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='added_cash',
            field=models.DecimalField(decimal_places=50, default=40000, max_digits=500),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='cash',
            field=models.DecimalField(decimal_places=50, default=40000, max_digits=500),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='leaderboard_portfolio_value',
            field=models.DecimalField(decimal_places=50, default=40000, max_digits=500),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='price_history',
            field=models.TextField(default='40000'),
        ),
    ]
