# Generated by Django 4.0.5 on 2022-09-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_guestuserinfo_leaderboard_portfolio_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestuserinfo',
            name='added_cash',
            field=models.DecimalField(decimal_places=50, default=60000, max_digits=500),
        ),
        migrations.AlterField(
            model_name='guestuserinfo',
            name='cash',
            field=models.DecimalField(decimal_places=50, default=60000, max_digits=500),
        ),
        migrations.AlterField(
            model_name='guestuserinfo',
            name='leaderboard_portfolio_value',
            field=models.DecimalField(decimal_places=50, default=60000, max_digits=500),
        ),
        migrations.AlterField(
            model_name='guestuserinfo',
            name='price_history',
            field=models.TextField(default='60000'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='added_cash',
            field=models.DecimalField(decimal_places=50, default=60000, max_digits=500),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='cash',
            field=models.DecimalField(decimal_places=50, default=60000, max_digits=500),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='leaderboard_portfolio_value',
            field=models.DecimalField(decimal_places=50, default=60000, max_digits=500),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='price_history',
            field=models.TextField(default='60000'),
        ),
    ]
